cmake_minimum_required(VERSION 4.4)

project(container)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(container container.cpp)
add_executable(sequence_container sequence_container.cpp)
add_executable(list_container list_container.cpp)
add_executable(additional_task_1 additional_task_1.cpp)
add_executable(additional_task_2 additional_task_2.cpp)
add_executable(additional_task_3 additional_task_3.cpp)
add_executable(additional_task_4 additional_task_4.cpp)